global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'digital'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: [':9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [':9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: [':9091']

  - job_name: 'dummy'  # This is a default value, it is mandatory.
    file_sd_configs:
      files:
        - targets.json


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - ':9093'
